Michael - Home Screen
seykafu/Shenkii pull request #30
Opened 2020-11-15 01:10 UTC by m3zhen

Home screen with image and text
missing:
- scroll function
- overlap text/image

2020-11-15 05:09 UTC, zhengwin requested changes
Everything looks good, i just left a comment regarding float. Flexbox is the standard way of aligning elements now and is much easier to use and maintain.

2020-11-15 05:09 UTC, zhengwin commented on new-frontend/src/pages/Home/index.module.css
> +    float: left;
instead of using float to place one div on the left and the other div on the right. You can use flexbox. Take a look here: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2020-11-15 05:09 UTC, zhengwin commented on new-frontend/src/pages/Home/index.module.css
> +    float: right;
instead of using float to place one div on the left and the other div on the right. You can use flexbox. Take a look here: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2020-12-11 02:46 UTC, zhengwin approved these changes
LGTM ! change the padding to use REM instead of %

2020-12-22 00:30 UTC, merged

2020-12-22 00:37 UTC, fakesquid approved these changes